-- CreateTable
CREATE TABLE "HealthCheck" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "headers" TEXT NOT NULL,
    "body" TEXT NOT NULL
);
